services:
  - type: web
    name: istanbul-traffic-forecast-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_DEBUG
        value: "0"
      - key: ADMIN_EMAILS
        value: demor.uzay@gmail.com
